package com.demo;

public class ExceptionDemo4 {
	
	public static void main(String[] args) {
		int a=30, b=0;
		try {
			int c=a/b;
			System.out.println("result = " +c);	
		}
		catch()
		{
			
		}
		
		
		
		
	}
}
